### ISSUE TITLE
Include library "podEnergyComp"

### ISSUE THREAD

**Issue by skumarorxa** [camroach87/pod-energy-comp#34]
Hi,
    There is no such library existing in the repo. Can you please push it to the repo.

Regards
Sanjeev Kumar

**Comment by camroach87** [comment]
Hi, this repo is the `podEnergyComp` library. You can install it using commands in the Build pane in RStudio. The `devtools::install_github("camroach87/pod-energy-comp")` command should work as well, though I haven't tested it yet. I'm currently tidying up the repo and will include instructions on how to install and use the package soon.
