### ISSUE TITLE
The command not working

### ISSUE THREAD

**Issue by skumarorxa** [camroach87/pod-energy-comp#38]
Hi Cameron,
                    The command "devtools::install_github("camroach87/pod-energy-comp")" is not working using Rstudio console

Downloading GitHub repo camroach87/pod-energy-comp@master
from URL https://api.github.com/repos/camroach87/pod-energy-comp/zipball/master
Installation failed: 404: Not Found (404)

Regards
Sanjeev Kumar

**Comment by camroach87** [comment]
Yes, I seem to be having that issue as well. Best thing for the moment is to build using RStudio. If you have RStudio installed, try using the Build -> Install and Restart menu option to install the package. That's working on my machine and what I've been using so far.

I'm just finishing off some bugfixes and will test to ensure the install_github command is working when I merge the v0_0_1 branch to master.

**Comment by skumarorxa** [comment]
Hi, I got it running. I used Rstudio earlier also but didn't create new project. After creating project. Using build pane was able to install all the necessary packages. Thanks for you quick reply.

**Comment by camroach87** [comment]
I have now merged the `v0_0_1` branch with `main`. I tested `devtools::install_github("camroach87/pod-energy-comp")` on my laptop and it appears to be working correctly now.
